version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: employee_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: employeedb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: employee_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: employee_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
